spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/sejongdeveloper
    username: sa
  jpa:
    hibernate:
      ddl-auto: update

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false

jwt:
  key: 12345678901234567890123456789012
